import { TextAlign } from '@shopify/react-native-skia';
import { Size, TextVariants, FilterVariant } from '../types';

export type State = {
  fonts: string[];
  sizes: Size[];
  textVariants: TextVariants | null;
  backdropVariants: Array<
    { id: string; color: string } | { id: string; colors: string[] }
  >;
  filterVariants: FilterVariant[];
};

export const configData: State = {
  fonts: ['Roboto'],
  sizes: [
    {
      label: { title: '1200x1200.title', desc: '1200x1200.desc' },
      id: '1200_1200',
      width: 1200,
      height: 1200,
      ratio: 0.29,
    },
  ],
  textVariants: {
    '1200_1200': [
      {
        title: {
          fontSize: 38,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Alice',
          width: 314,
          height: 77.3,
          top: 12,
          left: 15.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 500,
          fontFamily: 'Alice',
          width: 275.5,
          height: 45.2,
          top: 97,
          left: 16,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Alice',
          width: 144.5,
          height: 42.9,
          top: 35,
          left: 16,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 20,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Alice',
          width: 161,
          height: 63.3,
          top: 35,
          left: 170.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 28,
          lineHeight: 0.9,
          fontWeight: 600,
          fontFamily: 'Bitter',
          width: 254,
          height: 60.1,
          top: 12,
          left: 15.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 18,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Bitter',
          width: 277,
          height: 40.7,
          top: 336.5,
          left: 54.5,
          textAlign: TextAlign.Right,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 26,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Bitter',
          width: 222.5,
          height: 55.8,
          top: 177,
          left: 16,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 18,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Bitter',
          width: 208,
          height: 38.6,
          top: 329,
          left: 122.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 24,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Caveat',
          width: 239,
          height: 27.1,
          top: 168,
          left: 54,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 24,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Caveat',
          width: 239,
          height: 51.5,
          top: 171,
          left: 54,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Caveat',
          width: 299.5,
          height: 22.6,
          top: 20,
          left: 23,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Caveat',
          width: 299,
          height: 22.6,
          top: 329,
          left: 24.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 18,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Comfortaa',
          width: 283,
          height: 20.3,
          top: 37,
          left: 32.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 18,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Comfortaa',
          width: 285,
          height: 40.7,
          top: 311,
          left: 31.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 24,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Comfortaa',
          width: 283,
          height: 27.1,
          top: 40,
          left: 32.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 24,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Comfortaa',
          width: 285,
          height: 54.2,
          top: 315,
          left: 31.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 36,
          lineHeight: 0.7,
          fontWeight: 400,
          fontFamily: 'Cormorant',
          width: 315.5,
          height: 40.7,
          top: 75,
          left: 15,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 36,
          lineHeight: 0.7,
          fontWeight: 400,
          fontFamily: 'Cormorant',
          width: 314,
          height: 69.2,
          top: 333,
          left: 16.5,
          textAlign: TextAlign.Right,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Cormorant',
          width: 299.5,
          height: 22.6,
          top: 19,
          left: 23,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 46,
          lineHeight: 0.7,
          fontWeight: 500,
          fontFamily: 'Cormorant',
          width: 299.5,
          height: 124.8,
          top: 335.8,
          left: 23,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 24,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Commissioner',
          width: 145.5,
          height: 54.2,
          top: 156,
          left: 15,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 24,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Commissioner',
          width: 176,
          height: 81.4,
          top: 156,
          left: 162.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 46,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Commissioner',
          width: 298.5,
          height: 93.6,
          top: 13,
          left: 16,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 18,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Commissioner',
          width: 313,
          height: 20.3,
          top: 329,
          left: 17.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 42,
          lineHeight: 0.8,
          fontWeight: 500,
          fontFamily: 'EB Garamond',
          width: 299,
          height: 85.4,
          top: 172,
          left: 25.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 42,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'EB Garamond',
          width: 298.5,
          height: 85.4,
          top: 163,
          left: 24,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 24,
          lineHeight: 0.8,
          fontWeight: 500,
          fontFamily: 'EB Garamond',
          width: 299,
          height: 27.1,
          top: 16,
          left: 23.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 48,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'EB Garamond',
          width: 300,
          height: 141,
          top: 334,
          left: 23.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 28,
          lineHeight: 0.8,
          fontWeight: 500,
          fontFamily: 'Fira Sans',
          width: 299,
          height: 31.6,
          top: 16,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 28,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Fira Sans',
          width: 300,
          height: 57,
          top: 334,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 18,
          lineHeight: 1,
          fontWeight: 500,
          fontFamily: 'Fira Sans',
          width: 185,
          height: 20.3,
          top: 128,
          left: 146.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 18,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Fira Sans',
          width: 220,
          height: 40.7,
          top: 183,
          left: 25.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 14,
          lineHeight: 1,
          fontWeight: 500,
          fontFamily: 'Inter',
          width: 160.5,
          height: 15.8,
          top: 18,
          left: 162,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 40,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Inter',
          width: 298,
          height: 117.5,
          top: 326,
          left: 25.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 500,
          fontFamily: 'Inter',
          width: 160.5,
          height: 18.1,
          top: 33,
          left: 31,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Inter',
          width: 298,
          height: 18.1,
          top: 313,
          left: 30.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 48,
          lineHeight: 0.8,
          fontWeight: 500,
          fontFamily: 'Jost',
          width: 260,
          height: 97.6,
          top: 16,
          left: 70.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Jost',
          width: 253,
          height: 45.2,
          top: 236,
          left: 67.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 26,
          lineHeight: 0.8,
          fontWeight: 500,
          fontFamily: 'Jost',
          width: 284,
          height: 29.4,
          top: 7,
          left: 30.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 26,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Jost',
          width: 285,
          height: 52.9,
          top: 346,
          left: 30.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Karla',
          width: 168,
          height: 45.2,
          top: 210,
          left: 155.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 40,
          lineHeight: 0.7,
          fontWeight: 500,
          fontFamily: 'Karla',
          width: 299.5,
          height: 108.5,
          top: 212.8,
          left: 23,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 54,
          lineHeight: 0.7,
          fontWeight: 400,
          fontFamily: 'Karla',
          width: 274.3,
          height: 103.7,
          top: 329,
          left: 54.5,
          textAlign: TextAlign.Right,
          fill: '#ffffff',
        },
        description: {
          fontSize: 20,
          lineHeight: 0.7,
          fontWeight: 500,
          fontFamily: 'Karla',
          width: 299.5,
          height: 38.4,
          top: 23.8,
          left: 24,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 12,
          lineHeight: 0.8,
          fontWeight: 500,
          fontFamily: 'Lora',
          width: 285,
          height: 13.6,
          top: 282,
          left: 30.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 40,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Lora',
          width: 283,
          height: 117.5,
          top: 24,
          left: 31.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 12,
          lineHeight: 0.8,
          fontWeight: 500,
          fontFamily: 'Lora',
          width: 166,
          height: 13.6,
          top: 7,
          left: 86.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 40,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Lora',
          width: 283,
          height: 117.5,
          top: 133,
          left: 31.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 12,
          lineHeight: 0.8,
          fontWeight: 500,
          fontFamily: 'Manrope',
          width: 285,
          height: 13.6,
          top: 11,
          left: 30.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 40,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Manrope',
          width: 283,
          height: 117.5,
          top: 167,
          left: 31.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 0.8,
          fontWeight: 500,
          fontFamily: 'Manrope',
          width: 160,
          height: 18.1,
          top: 11,
          left: 163.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 16,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Manrope',
          width: 300,
          height: 18.1,
          top: 154,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 0.8,
          fontWeight: 500,
          fontFamily: 'Merriweather',
          width: 236,
          height: 18.1,
          top: 24,
          left: 30.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 28,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Merriweather',
          width: 283,
          height: 63.3,
          top: 144,
          left: 32.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 12,
          lineHeight: 0.8,
          fontWeight: 500,
          fontFamily: 'Merriweather',
          width: 236,
          height: 13.6,
          top: 320,
          left: 30.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 36,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Merriweather',
          width: 284,
          height: 122,
          top: 29,
          left: 31.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 40,
          lineHeight: 0.8,
          fontWeight: 500,
          fontFamily: 'Montserrat',
          width: 284,
          height: 81.4,
          top: 118,
          left: 31.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 12,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Montserrat',
          width: 169,
          height: 27.1,
          top: 27,
          left: 146.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 14,
          lineHeight: 1,
          fontWeight: 500,
          fontFamily: 'Montserrat',
          width: 284,
          height: 15.8,
          top: 155,
          left: 32.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 24,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Montserrat',
          width: 284,
          height: 48.8,
          top: 163,
          left: 30.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 22,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Oswald',
          width: 167.5,
          height: 24.9,
          top: 26,
          left: 163,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 22,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Oswald',
          width: 168,
          height: 44.7,
          top: 320,
          left: 162.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Oswald',
          width: 291.5,
          height: 18.1,
          top: 32,
          left: 31,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Oswald',
          width: 284,
          height: 18.1,
          top: 320,
          left: 30.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Pacifico',
          width: 284,
          height: 18.1,
          top: 8,
          left: 31.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 30,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Pacifico',
          width: 283.5,
          height: 67.8,
          top: 144,
          left: 32,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 26,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Pacifico',
          width: 284,
          height: 29.4,
          top: 161,
          left: 30.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 26,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Pacifico',
          width: 283.5,
          height: 58.8,
          top: 168,
          left: 32,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 14,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Playfair Display',
          width: 284,
          height: 15.8,
          top: 26,
          left: 21.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 32,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Playfair Display',
          width: 283.5,
          height: 72.3,
          top: 141,
          left: 24,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 24,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Playfair Display',
          width: 284,
          height: 27.1,
          top: 24,
          left: 22.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 24,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Playfair Display',
          width: 283.5,
          height: 54.2,
          top: 330,
          left: 24,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 10,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Playfair Display SC',
          width: 284,
          height: 11.3,
          top: 24,
          left: 22.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 24,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Playfair Display SC',
          width: 283.5,
          height: 54.2,
          top: 175,
          left: 30,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Playfair Display SC',
          width: 284,
          height: 18.1,
          top: 16,
          left: 22.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 36,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Playfair Display SC',
          width: 301.5,
          height: 162.7,
          top: 334,
          left: 20,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Podkova',
          width: 300,
          height: 22.6,
          top: 20,
          left: 23.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 20,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Podkova',
          width: 299,
          height: 42.9,
          top: 324,
          left: 23.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Podkova',
          width: 145,
          height: 18.1,
          top: 15,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 36,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Podkova',
          width: 299,
          height: 77.3,
          top: 332,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Prata',
          width: 299,
          height: 18.1,
          top: 15,
          left: 23.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 30,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Prata',
          width: 299,
          height: 64.4,
          top: 142,
          left: 23.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 30,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Prata',
          width: 299,
          height: 33.9,
          top: 15,
          left: 23.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 30,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Prata',
          width: 299,
          height: 64.4,
          top: 331,
          left: 24.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 10,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Press Start 2P',
          width: 145,
          height: 22.6,
          top: 138,
          left: 8.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 10,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Press Start 2P',
          width: 167,
          height: 33.9,
          top: 138,
          left: 169.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 14,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Press Start 2P',
          width: 145,
          height: 31.6,
          top: 50,
          left: 15.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 14,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Press Start 2P',
          width: 231,
          height: 47.5,
          top: 174,
          left: 15.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 14,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'PT Mono',
          width: 145,
          height: 15.8,
          top: 14,
          left: 15.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 22,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'PT Mono',
          width: 253,
          height: 49.7,
          top: 174,
          left: 15.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 14,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'PT Mono',
          width: 300,
          height: 15.8,
          top: 72,
          left: 15.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 14,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'PT Mono',
          width: 300,
          height: 31.6,
          top: 72,
          left: 15.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'PT Sans',
          width: 230,
          height: 22.6,
          top: 35,
          left: 84.5,
          textAlign: TextAlign.Right,
          fill: '#ffffff',
        },
        description: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'PT Sans',
          width: 238,
          height: 45.2,
          top: 313,
          left: 30.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 24,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'PT Sans',
          width: 230,
          height: 27.1,
          top: 167,
          left: 92.5,
          textAlign: TextAlign.Right,
          fill: '#ffffff',
        },
        description: {
          fontSize: 24,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'PT Sans',
          width: 238,
          height: 54.2,
          top: 330,
          left: 24.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'PT Serif',
          width: 283,
          height: 18.1,
          top: 331,
          left: 32.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 34,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'PT Serif',
          width: 300,
          height: 76.8,
          top: 16,
          left: 22.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 10,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'PT Serif',
          width: 283,
          height: 11.3,
          top: 20,
          left: 31.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 42,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'PT Serif',
          width: 300,
          height: 123.4,
          top: 308,
          left: 23.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Public Sans',
          width: 281,
          height: 22.6,
          top: 306,
          left: 33.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 38,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Public Sans',
          width: 300,
          height: 111.6,
          top: 14,
          left: 23.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Public Sans',
          width: 281,
          height: 18.1,
          top: 20,
          left: 31.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 36,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Public Sans',
          width: 300,
          height: 105.8,
          top: 121,
          left: 23.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Raleway',
          width: 281,
          height: 18.1,
          top: 31,
          left: 25.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 38,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Raleway',
          width: 300,
          height: 111.6,
          top: 90,
          left: 24.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 24,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Raleway',
          width: 199,
          height: 54.2,
          top: 39,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 24,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Raleway',
          width: 300,
          height: 48.8,
          top: 307,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 14,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Roboto',
          width: 184,
          height: 15.8,
          top: 214,
          left: 139.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 24,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Roboto',
          width: 300,
          height: 54.2,
          top: 200,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 26,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Roboto',
          width: 184,
          height: 58.8,
          top: 14,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Roboto',
          width: 300,
          height: 18.1,
          top: 178,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 38,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Rubik',
          width: 299,
          height: 77.3,
          top: 19,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 38,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Rubik',
          width: 298,
          height: 111.6,
          top: 333,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 14,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Rubik',
          width: 214,
          height: 15.8,
          top: 25,
          left: 31.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 26,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Rubik',
          width: 284,
          height: 52.9,
          top: 54,
          left: 31.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Russo One',
          width: 174,
          height: 45.2,
          top: 25,
          left: 148.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 20,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Russo One',
          width: 176,
          height: 58.8,
          top: 182,
          left: 145.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Russo One',
          width: 262,
          height: 22.6,
          top: 12,
          left: 22.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 36,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Russo One',
          width: 268,
          height: 138.3,
          top: 333,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 14,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Space Grotesk',
          width: 262,
          height: 15.8,
          top: 328,
          left: 61.5,
          textAlign: TextAlign.Right,
          fill: '#ffffff',
        },
        description: {
          fontSize: 30,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Space Grotesk',
          width: 247,
          height: 88.1,
          top: 14,
          left: 22.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 12,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Space Grotesk',
          width: 230,
          height: 13.6,
          top: 19,
          left: 93.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 30,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Space Grotesk',
          width: 230,
          height: 88.1,
          top: 313,
          left: 90.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 30,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Yanone Kaffeesatz',
          width: 184,
          height: 33.9,
          top: 43,
          left: 30.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 30,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Yanone Kaffeesatz',
          width: 230,
          height: 67.8,
          top: 301,
          left: 85.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 24,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Yanone Kaffeesatz',
          width: 184,
          height: 27.1,
          top: 70,
          left: 13.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 36,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Yanone Kaffeesatz',
          width: 230,
          height: 73.2,
          top: 341,
          left: 14.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 12,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Yeseva One',
          width: 184,
          height: 13.6,
          top: 11,
          left: 14.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 44,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Yeseva One',
          width: 316,
          height: 169,
          top: 341,
          left: 14.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 32,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Yeseva One',
          width: 214,
          height: 65.1,
          top: 17,
          left: 24.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 20,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Yeseva One',
          width: 300,
          height: 40.7,
          top: 329,
          left: 22.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 22,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'TekturNarrow',
          width: 214,
          height: 24.9,
          top: 17,
          left: 24.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 22,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'TekturNarrow',
          width: 184,
          height: 49.7,
          top: 329,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 22,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'TekturNarrow',
          width: 176,
          height: 24.9,
          top: 168,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 22,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'TekturNarrow',
          width: 197,
          height: 49.7,
          top: 173,
          left: 125.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Tektur',
          width: 176,
          height: 45.2,
          top: 12,
          left: 15.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 40,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Tektur',
          width: 313,
          height: 135.6,
          top: 341,
          left: 16.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 14,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Tektur',
          width: 176,
          height: 15.8,
          top: 10,
          left: 160,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 14,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Tektur',
          width: 161,
          height: 31.6,
          top: 341,
          left: 167.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Ramona',
          width: 253,
          height: 18.1,
          top: 135,
          left: 46.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 32,
          lineHeight: 1,
          fontWeight: 600,
          fontFamily: 'Ramona',
          width: 285,
          height: 72.3,
          top: 147,
          left: 30.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 24,
          lineHeight: 1,
          fontWeight: 600,
          fontFamily: 'Ramona',
          width: 261,
          height: 27.1,
          top: 14,
          left: 39.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 24,
          lineHeight: 1,
          fontWeight: 600,
          fontFamily: 'Ramona',
          width: 285,
          height: 54.2,
          top: 329,
          left: 31.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 24,
          lineHeight: 1,
          fontWeight: 600,
          fontFamily: 'Pilowlava',
          width: 261,
          height: 54.2,
          top: 168,
          left: 39.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 24,
          lineHeight: 1,
          fontWeight: 600,
          fontFamily: 'Pilowlava',
          width: 285,
          height: 81.4,
          top: 171,
          left: 31.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 34,
          lineHeight: 1,
          fontWeight: 600,
          fontFamily: 'Pilowlava',
          width: 315,
          height: 76.8,
          top: 94,
          left: 15.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 34,
          lineHeight: 1,
          fontWeight: 600,
          fontFamily: 'Pilowlava',
          width: 314,
          height: 153.7,
          top: 331,
          left: 16.5,
          textAlign: TextAlign.Right,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 26,
          lineHeight: 1,
          fontWeight: 600,
          fontFamily: 'Pilowlava',
          width: 315,
          height: 58.8,
          top: 14,
          left: 16.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 26,
          lineHeight: 1,
          fontWeight: 600,
          fontFamily: 'Pilowlava',
          width: 314,
          height: 88.1,
          top: 337,
          left: 15.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 600,
          fontFamily: 'Pilowlava',
          width: 315,
          height: 18.1,
          top: 14,
          left: 16.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 600,
          fontFamily: 'Pilowlava',
          width: 314,
          height: 36.2,
          top: 337,
          left: 14.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 14,
          lineHeight: 1,
          fontWeight: 600,
          fontFamily: 'ouroboros',
          width: 315,
          height: 15.8,
          top: 139,
          left: 14.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 38,
          lineHeight: 0.8,
          fontWeight: 600,
          fontFamily: 'ouroboros',
          width: 314,
          height: 111.6,
          top: 147,
          left: 15.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 12,
          lineHeight: 1,
          fontWeight: 600,
          fontFamily: 'ouroboros',
          width: 315,
          height: 13.6,
          top: 14,
          left: 16.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 32,
          lineHeight: 1,
          fontWeight: 600,
          fontFamily: 'ouroboros',
          width: 314,
          height: 108.5,
          top: 337,
          left: 14.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 600,
          fontFamily: 'ouroboros',
          width: 229,
          height: 22.6,
          top: 21,
          left: 18.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 20,
          lineHeight: 0.8,
          fontWeight: 600,
          fontFamily: 'ouroboros',
          width: 283,
          height: 40.7,
          top: 322,
          left: 32.5,
          textAlign: TextAlign.Right,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 12,
          lineHeight: 1,
          fontWeight: 600,
          fontFamily: 'ouroboros',
          width: 229,
          height: 13.6,
          top: 279,
          left: 55.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 32,
          lineHeight: 0.8,
          fontWeight: 600,
          fontFamily: 'ouroboros',
          width: 300,
          height: 94,
          top: 231,
          left: 22.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 600,
          fontFamily: 'murmure',
          width: 229,
          height: 22.6,
          top: 25,
          left: 22.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 46,
          lineHeight: 0.8,
          fontWeight: 600,
          fontFamily: 'murmure',
          width: 292,
          height: 93.6,
          top: 329,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'murmure',
          width: 253,
          height: 22.6,
          top: -55.1,
          left: -126.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 46,
          lineHeight: 0.8,
          fontWeight: 600,
          fontFamily: 'murmure',
          width: 284,
          height: 93.6,
          top: 66.9,
          left: -142.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'murmure',
          width: 134.5,
          height: 18.1,
          top: 15,
          left: 21,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'murmure',
          width: 175,
          height: 18.1,
          top: 16,
          left: 148.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Lack',
          width: 246,
          height: 22.6,
          top: 158,
          left: 69.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Lack',
          width: 300,
          height: 45.2,
          top: 161,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Lack',
          width: 246,
          height: 22.6,
          top: 12,
          left: 20.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Lack',
          width: 214,
          height: 45.2,
          top: 328,
          left: 109.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Lack',
          width: 246,
          height: 18.1,
          top: 16,
          left: 22.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 42,
          lineHeight: 0.7,
          fontWeight: 400,
          fontFamily: 'Lack',
          width: 299,
          height: 147.1,
          top: 326,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Lack',
          width: 300,
          height: 18.1,
          top: 16,
          left: 22.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Lack',
          width: 299,
          height: 36.2,
          top: 326,
          left: 23.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 40,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Lack',
          width: 300,
          height: 81.4,
          top: 202,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Lack',
          width: 299,
          height: 36.2,
          top: 24,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 32,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Lack',
          width: 300,
          height: 65.1,
          top: 33,
          left: 23.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 24,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Lack',
          width: 299,
          height: 54.2,
          top: 187,
          left: 24.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 34,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Ambidexter',
          width: 178.5,
          height: 69.2,
          top: 340,
          left: 152.5,
          textAlign: TextAlign.Right,
          fill: '#ffffff',
        },
        description: {
          fontSize: 34,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Ambidexter',
          width: 299,
          height: 69.2,
          top: 15,
          left: 31.5,
          textAlign: TextAlign.Right,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Ambidexter',
          width: 284,
          height: 18.1,
          top: 8,
          left: 32,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 42,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Ambidexter',
          width: 314,
          height: 123.4,
          top: 110,
          left: 16.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 18,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'DRUZHOK',
          width: 300,
          height: 20.3,
          top: 6,
          left: 24.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 42,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'DRUZHOK',
          width: 301,
          height: 161.4,
          top: 334,
          left: 21.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 22,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'DRUZHOK',
          width: 300,
          height: 24.9,
          top: 10,
          left: 24.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 22,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'DRUZHOK',
          width: 301,
          height: 44.7,
          top: 339,
          left: 21.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 22,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Finlandica',
          width: 208,
          height: 24.9,
          top: 170,
          left: 116.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 22,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Finlandica',
          width: 215.5,
          height: 44.7,
          top: 178,
          left: 116.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 28,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Finlandica',
          width: 190.5,
          height: 57,
          top: 71,
          left: 140,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 28,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Finlandica',
          width: 297,
          height: 57,
          top: 175,
          left: 24.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 32,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Lithium_tf',
          width: 190.5,
          height: 65.1,
          top: 13,
          left: 22,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 32,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Lithium_tf',
          width: 297,
          height: 65.1,
          top: 332,
          left: 20.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Lithium_tf',
          width: 139.5,
          height: 22.6,
          top: 75,
          left: 15,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 20,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Lithium_tf',
          width: 161,
          height: 40.7,
          top: 74,
          left: 169.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Onest',
          width: 168.5,
          height: 40.7,
          top: 12,
          left: 155,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 32,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Onest',
          width: 315,
          height: 65.1,
          top: 128,
          left: 16.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Onest',
          width: 276.5,
          height: 22.6,
          top: 12,
          left: 15,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 40,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Onest',
          width: 315,
          height: 117.5,
          top: 334,
          left: 15.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Onest',
          width: 315.5,
          height: 18.1,
          top: 12,
          left: 15,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 40,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Onest',
          width: 315,
          height: 117.5,
          top: 177,
          left: 15.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 24,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Onest',
          width: 315.5,
          height: 27.1,
          top: 12,
          left: 15,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 24,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Onest',
          width: 315,
          height: 48.8,
          top: 333,
          left: 16.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 24,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Onest',
          width: 177,
          height: 48.8,
          top: 10,
          left: 154.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 24,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Onest',
          width: 177,
          height: 70.5,
          top: 147,
          left: 154.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 28,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Onest',
          width: 277,
          height: 31.6,
          top: 6,
          left: 15.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 28,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Onest',
          width: 269,
          height: 57,
          top: 339,
          left: 63.5,
          textAlign: TextAlign.Right,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Unbounded',
          width: 244,
          height: 18.1,
          top: 331,
          left: 47.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 38,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Unbounded',
          width: 311,
          height: 146,
          top: 12,
          left: 15.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 34,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Unbounded',
          width: 312,
          height: 69.2,
          top: 15,
          left: 17.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 20,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Unbounded',
          width: 316,
          height: 40.7,
          top: 167,
          left: 16.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Unbounded',
          width: 230,
          height: 45.2,
          top: 12,
          left: 93.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 20,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Unbounded',
          width: 230,
          height: 45.2,
          top: 166,
          left: 91.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 28,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Unbounded',
          width: 314,
          height: 57,
          top: 6,
          left: 15.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 28,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Unbounded',
          width: 230,
          height: 107.6,
          top: 260,
          left: 100.5,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
      },
      {
        title: {
          fontSize: 42,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Roboto',
          width: 329.5,
          height: 85.4,
          top: 172,
          left: 8,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 42,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Roboto',
          width: 328.5,
          height: 123.4,
          top: 165,
          left: 9,
          textAlign: TextAlign.Left,
          fill: '#495bff',
        },
        backId: '#333333',
      },
      {
        title: {
          fontSize: 18,
          lineHeight: 0.9,
          fontWeight: 600,
          fontFamily: 'Raleway',
          width: 256.5,
          height: 20.3,
          top: 4,
          left: 43,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 18,
          lineHeight: 0.9,
          fontWeight: 600,
          fontFamily: 'Raleway',
          width: 268,
          height: 38.6,
          top: 345,
          left: 38.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        backId: '#333333',
      },
      {
        title: {
          fontSize: 20,
          lineHeight: 0.9,
          fontWeight: 500,
          fontFamily: 'Montserrat',
          width: 217.5,
          height: 22.6,
          top: 31,
          left: 29,
          textAlign: TextAlign.Left,
          fill: '#eb5029',
        },
        description: {
          fontSize: 20,
          lineHeight: 0.9,
          fontWeight: 500,
          fontFamily: 'Montserrat',
          width: 219.5,
          height: 42.9,
          top: 163,
          left: 29,
          textAlign: TextAlign.Left,
          fill: '#eb5029',
        },
        backId: '#333333',
      },
      {
        title: {
          fontSize: 10,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Manrope',
          width: 122.5,
          height: 11.3,
          top: 6,
          left: 8,
          textAlign: TextAlign.Left,
          fill: '#ffff05',
        },
        description: {
          fontSize: 10,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Manrope',
          width: 131.5,
          height: 22.6,
          top: 342,
          left: 9,
          textAlign: TextAlign.Left,
          fill: '#ffff05',
        },
        backId: '#333333',
      },
      {
        title: {
          fontSize: 12,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Jost',
          width: 178.5,
          height: 13.6,
          top: 315,
          left: 88.5,
          textAlign: TextAlign.Center,
          fill: '#ffffff',
        },
        description: {
          fontSize: 48,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Jost',
          width: 330.5,
          height: 141,
          top: 1,
          left: 7,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        backId: '#333333',
      },
      {
        title: {
          fontSize: 28,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Inter',
          width: 167.5,
          height: 60.1,
          top: 169,
          left: 10,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 28,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Inter',
          width: 232.5,
          height: 88.6,
          top: 164,
          left: 57,
          textAlign: TextAlign.Left,
          fill: '#7dfa79',
        },
        backId: '#333333',
      },
      {
        title: {
          fontSize: 58,
          lineHeight: 0.8,
          fontWeight: 600,
          fontFamily: 'Manrope',
          width: 329.5,
          height: 118,
          top: 352,
          left: 7,
          textAlign: TextAlign.Left,
          fill: '#fffc41',
        },
        description: {
          fontSize: 8,
          lineHeight: 1,
          fontWeight: 500,
          fontFamily: 'Manrope',
          width: 140.5,
          height: 9,
          top: 8,
          left: 10,
          textAlign: TextAlign.Left,
          fill: '#fffc41',
        },
        backId: '#C0C0C0',
      },
      {
        title: {
          fontSize: 24,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Inter',
          width: 169.5,
          height: 51.5,
          top: 169,
          left: 11,
          textAlign: TextAlign.Left,
          fill: '#ffffff',
        },
        description: {
          fontSize: 24,
          lineHeight: 0.9,
          fontWeight: 400,
          fontFamily: 'Inter',
          width: 272,
          height: 51.5,
          top: 171,
          left: 62.5,
          textAlign: TextAlign.Left,
          fill: '#2e64d6',
        },
        backId: '#C0C0C0',
      },
      {
        title: {
          fontSize: 14,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'DRUZHOK',
          width: 300,
          height: 15.8,
          top: 23,
          left: 19.5,
          textAlign: TextAlign.Center,
          fill: '#8500D7',
        },
        description: {
          fontSize: 44,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'DRUZHOK',
          width: 311,
          height: 169,
          top: 342,
          left: 19.5,
          textAlign: TextAlign.Center,
          fill: '#8500D7',
        },
        backId: '#C0C0C0',
      },
      {
        title: {
          fontSize: 58,
          lineHeight: 0.8,
          fontWeight: 600,
          fontFamily: 'Manrope',
          width: 329.5,
          height: 118,
          top: 352,
          left: 7,
          textAlign: TextAlign.Left,
          fill: '#45C544',
        },
        description: {
          fontSize: 8,
          lineHeight: 1,
          fontWeight: 500,
          fontFamily: 'Manrope',
          width: 140.5,
          height: 9,
          top: 8,
          left: 10,
          textAlign: TextAlign.Left,
          fill: '#303030',
        },
        backId: '#F3EBDE',
      },
      {
        title: {
          fontSize: 28,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Inter',
          width: 239,
          height: 57,
          top: 11,
          left: 14,
          textAlign: TextAlign.Left,
          fill: '#f05631',
        },
        description: {
          fontSize: 28,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Inter',
          width: 239,
          height: 82.3,
          top: 338,
          left: 14,
          textAlign: TextAlign.Left,
          fill: '#2f45c8',
        },
        backId: '#F3EBDE',
      },
      {
        title: {
          fontSize: 16,
          lineHeight: 1,
          fontWeight: 400,
          fontFamily: 'Unbounded',
          width: 300,
          height: 18.1,
          top: 23,
          left: 19.5,
          textAlign: TextAlign.Left,
          fill: '#AC63F4',
        },
        description: {
          fontSize: 44,
          lineHeight: 0.8,
          fontWeight: 400,
          fontFamily: 'Lack',
          width: 311,
          height: 169,
          top: 342,
          left: 19.5,
          textAlign: TextAlign.Left,
          fill: '#AC63F4',
        },
        backId: '#F6F2E6',
      },
    ],
    '735_1102': [],
    '1200_628': [],
    '1024_768': [],
    '1080_1920': [],
  },
  backdropVariants: [
    {
      id: '#F6F2E6',
      color: '#F6F2E6',
    },
    {
      id: '#F3EBDE',
      color: '#F3EBDE',
    },
    {
      id: '#333333',
      color: '#333333',
    },
    {
      id: '#C0C0C0',
      color: '#C0C0C0',
    },
    {
      id: '#6CCFBA',
      color: '#6CCFBA',
    },
    {
      id: '#2E64D6',
      color: '#2E64D6',
    },
    {
      id: '#7944BE',
      color: '#7944BE',
    },
    {
      id: '#EF40A5',
      color: '#EF40A5',
    },
    {
      id: '#FF5A5F',
      color: '#FF5A5F',
    },
    {
      id: '#FFA600',
      color: '#FFA600',
    },
    {
      id: 'grad_01',
      colors: ['#A3DEFF', '#15FDC5'],
    },
    {
      id: 'grad_02',
      colors: ['#BCD3FC', '#6091FA'],
    },
    {
      id: 'grad_03',
      colors: ['#EEA2FB', '#9260FD'],
    },
    {
      id: 'grad_04',
      colors: ['#FF65AF', '#F4C4F3'],
    },
    {
      id: 'grad_05',
      colors: ['#FF5A5F', '#FFCDBD'],
    },
    {
      id: 'grad_06',
      colors: ['#FEE140', '#FA8970'],
    },
  ],
  filterVariants: [
    {
      id: 'grayscale',
      name: 'grayscale',
    },
    {
      id: 'pixelate',
      name: 'pixelate',
    },
    {
      id: 'blendcolor30',
      name: 'blendcolor',
      value: 0.3,
    },
    {
      id: 'blendcolor50',
      name: 'blendcolor',
      value: 0.5,
    },
    {
      id: 'blendcolor70',
      name: 'blendcolor',
      value: 0.7,
    },
    {
      id: 'brightness-5',
      name: 'brightness',
      value: -0.05,
    },
    {
      id: 'brightness-25',
      name: 'brightness',
      value: -0.25,
    },
    {
      id: 'brightness-40',
      name: 'brightness',
      value: -0.4,
    },
    {
      id: 'contrast-45',
      name: 'contrast',
      value: -0.45,
    },
    {
      id: 'contrast30',
      name: 'contrast',
      value: 0.3,
    },
    {
      id: 'saturation-45',
      name: 'saturation',
      value: -0.45,
    },
    {
      id: 'saturation50',
      name: 'saturation',
      value: 0.5,
    },
    {
      id: 'blur100',
      name: 'blur',
      value: 1,
    },
    {
      id: 'blur50',
      name: 'blur',
      value: 0.5,
    },
    {
      id: 'blur15',
      name: 'blur',
      value: 0.15,
    },
  ],
};
